---
- hosts: all
  gather_facts: true

  roles:
    - role: "ansible-role-pidev"
      pidev_secrets:
        access-key: "{{ lookup('env','ACCESS_KEY') or 'test' }}"
        secret-key: "{{ lookup('env','SECRET_KEY') or 'test_secret' }}"
...
