---
- name: reload firewalld
  shell: "firewall-cmd --reload"

- name: restart docker
  service:
    name: "docker"
    state: "restarted"

- name: deploy stack
  shell: "./deploy_stack.sh --no-auth"
  args:
    chdir: "{{ pidev_user.homedir }}/openfaas/faas/"
  become: true
  become_user: "{{ pidev_user.name}}"
  become_method: "su"
  register: stack_deploy
  failed_when: false

- name: deploy functions
  shell: "faas-cli build && faas-cli deploy"
  args:
    chdir: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
  with_items:
    - "{{ pidev_piedpiper_faas }}"
  become: true
  become_user: "{{ pidev_user.name }}"
  become_method: "su"

- name: install picli
  shell: "python3 setup.py install"
  args:
    chdir: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
  with_items:
    - "{{ pidev_piedpiper_cli }}"

- name: build gman
  shell: "docker build -t gman ."
  args:
    chdir: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
  with_items:
    - "{{ pidev_piperci_gman }}"
