---
- name: this block contains tasks related to apt_packages
  block:

    - name: ensure apt cache is up to date (not idempotent)
      apt:
        update_cache: "yes"
    
    - name: ensure aptitude is installed
      apt:
        name: "aptitude"
        state: "present"
    
    - name: ensure system packages are installed
      apt:
        name: "{{ pidev_packages }}"
        state: "present"
        
  tags:
    - apt_packages
