---
- name: this block contains tasks related to docker_images
  block:

    - name: ensure docker images are installed and updated
      docker_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
      with_items:
        - "{{ pidev_docker_images }}"
          
  tags:
    - docker_images
...
