---
- name: this block contains tasks related to firewalld
  block:
    - name: get current zones associated with internal zone
      shell: "firewall-cmd --zone=internal --list-interfaces"
      changed_when: false
      register: internal_interfaces
    
    - name: get list of all enabled services on firewall internal zone
      shell: "firewall-cmd --zone=internal --list-services"
      changed_when: false
      register: get_fw_internal_services
    
    - name: get list of all enabled ports on firewall internal zone
      shell: "firewall-cmd --zone=internal --list-ports"
      changed_when: false
      register: get_fw_internal_ports
    
    - name: get list of all enabled ports on firewall public zone
      shell: "firewall-cmd --list-ports"
      changed_when: false
      register: get_fw_default_ports
    
    - name: ensure required services enabled on internal firewall zone
      shell: "firewall-cmd --permanent --zone=internal --add-service={{ item }}"
      when: item not in get_fw_internal_services.stdout
      with_items:
        - http
        - https
        - ssh
      notify: reload firewalld
    
    - name: ensure required ports enabled on internal firewall zone
      shell: "firewall-cmd --permanent --zone=internal --add-port={{ item }}"
      when: item not in get_fw_internal_ports.stdout
      with_items:
        - "80/tcp"
        - "443/tcp"
        - "22/tcp"
      notify: reload firewalld
    
    - name: ensure required services enabled on default firewall zone
      shell: "firewall-cmd --permanent --zone=internal --add-service={{ item }}"
      when: item not in get_fw_internal_services.stdout
      with_items:
        - http
        - https
        - ssh
      notify: reload firewalld
    
    - name: ensure required ports enabled on default firewall zone
      shell: "firewall-cmd --permanent --add-port={{ item }}"
      when: item not in get_fw_default_ports.stdout
      with_items:
        - "80/tcp"
        - "443/tcp"
        - "22/tcp"
      notify: reload firewalld
    
    - meta: flush_handlers
  tags:
    - firewalld
...
