---
- name: this block contains tasks related to piedpiper_cli
  block:

    - name: ensures latest versions of pied piper cli has been git cloned
      git:
        repo: "https://github.com/{{ item.org_name }}/{{ item.name }}.git"
        dest: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
        clone: "yes"
        version: "{{ item.version | default(omit) }}"
        force: "yes"
      with_items:
        - "{{ pidev_piedpiper_cli }}"
      become: true
      become_user: "{{ pidev_user.name }}"
      become_method: "su"
      notify:
        - install picli

  tags:
    - piedpiper_cli
