---
- name: this block contains tasks related to piedpiper_cli
  block:

    - name: ensures latest versions of pied piper cli has been git cloned (not idempotent)
      git:
        repo: "https://github.com/{{ item.org_name }}/{{ item.name }}.git"
        dest: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
        clone: "yes"
        version: "{{ item.version | default(omit) }}"
        force: "yes"
      with_items:
        - "{{ pidev_piedpiper_cli }}"
      become: true
      become_user: "{{ pidev_user.name }}"
      become_method: "su"

    - name: ensures latest versions of picli is installed (not idempotent)
      shell: "python3 setup.py install"
      args:
        chdir: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
      with_items:
        - "{{ pidev_piedpiper_cli }}"

  tags:
    - piedpiper_cli
