---
- name: this block contains tasks related to piperci_gman
  block:

    - name: ensures latest versions of piperci gman has been git cloned
      git:
        repo: "https://gitlab.com/{{ item.org_name }}/{{ item.name }}.git"
        dest: "{{ pidev_user.homedir }}/{{ item.org_name }}/{{ item.name }}/"
        clone: "yes"
        version: "{{ item.version | default(omit) }}"
        force: "yes"
      with_items:
        - "{{ pidev_piperci_gman }}"
      become: true
      become_user: "{{ pidev_user.name }}"
      become_method: "su"
      notify:
        - build gman

  tags:
    - piperci_gman
